sequenceDiagram
    actor U as User
    participant B as Bot
    actor W as Admin
    U->>B: start
    B->>U: Приветствует
    loop Запрос цитаты
        U->>B: Запрашивает цитату
        B->>U: Уточняет из каого фильма нужна цитата
        !!!!!!!!!!!!!!!

    end
    U->>B: Подтверждает заказ
    B->>W: Сообщает о заказе
    W->>U: Приносит заказ
    W->>B: Сообщает, что выдал заказ
    U->>B: Подтверждает получение